### PR TITLE
Removing broken plates

### PR DESCRIPTION
**Pull request by joshmoore**
plate5 is not loading as a single plate. Removing for the moment. We'll need to have a list of these problematic plates that we come back to.

Perhaps only merge once human2 is all the way in?

### CODE REVIEW

**Comment by joshmoore** [comment]
Plate 10 and 1 seem to also have issues. May have to go through them systematically.

**Comment by joshmoore** [comment]
Plate_1_Redo_L23_s3_w3.TIF needs to go as well. I'll produce a list of everything that _doesn't_ parse as SPW: true.

**Comment by joshmoore** [comment]
9 plates correctly identified:

```
omero@9ea7bf42215b:~$ grep Group act1.out | grep "SPW: true" | wc
      9      67    1298
```

22K files ungrouped:

```
omero@9ea7bf42215b:~$ grep Group act1.out | grep "SPW: false" | wc
  22743  168906 3562227
```

specifically here:

```
omero@9ea7bf42215b:~$ grep Group act1.out | grep "SPW: false" | cut -f1-6 -d/ | sort | uniq -c
    306 # Group: /idr/filesets/idr0008-rohn-actinome/original-actinome2/PLate5_Actinome2
    501 # Group: /idr/filesets/idr0008-rohn-actinome/original-actinome2/Plate1_Actinome2
   4029 # Group: /idr/filesets/idr0008-rohn-actinome/original-actinome2/Plate3_Actinome2
   3396 # Group: /idr/filesets/idr0008-rohn-actinome/original-actinome2/Plate4_Actinome2
   3438 # Group: /idr/filesets/idr0008-rohn-actinome/original-actinome2/Plate6_Actinome2
   3672 # Group: /idr/filesets/idr0008-rohn-actinome/original-actinome2/Plate7_Actinome2
   3849 # Group: /idr/filesets/idr0008-rohn-actinome/original-actinome2/Plate8_Actinome2
   3552 # Group: /idr/filesets/idr0008-rohn-actinome/original-actinome2/Plate9_Actinome2
```

**Comment by manics** [comment]
How about a standard `idrNNNN-xxxx-xxxxxxxx/import_failures.txt` containg the problematic paths?

**Comment by joshmoore** [comment]
That certainly would work at the plate level, but part of my problem is that some plate directories have unrelated files. I might be able to fix that by specifying specific files to import rather than the directory, but it will require some playing. Here some tool to help compute the imports might be useful.

**Pull request merged**
