### PR TITLE
add config for organism

### PR DESCRIPTION
**Pull request by atarkowska**
This PR allows to add organism without deleting map annotations

```
bin/omero metadata populate --context bulkmap --cfg /tmp/idr-metadata/idr0012-fuchs-cellmorph/screenA/idr0012-screenA-bulkmap-config-organism.yml  Screen:1202

bin/omero metadata populate --context bulkmap --cfg /tmp/idr-metadata/idr0019-sero-nfkappab/screenA/idr0019-screenA-bulkmap-config-compound.yml Screen:1203     
```

see http://10.0.51.135/web/webclient/?show=well-1000858

Requires discussion cc: @joshmoore @manics

### CODE REVIEW

**Comment by eleanorwilliams** [comment]
This fix might be fine, but one question is would we expose this 'fixing file' to the outside world?  Or would we just provide the corrected bulkmap file even though its not tested?

**Comment by atarkowska** [comment]
I am guessing this is just a patch and perhaps should be merged with the main bulk-config. How about if we introduce patching strategy? When parsing do we take version to the account?

**Comment by joshmoore** [comment]
From meeting, these files can be added for the moment. Longer-term, hopefully the CLI will permit selecting only some namespaces. (An alternative that occurs to me would be to split the configuration files in a single directory) cc: @manics

**Comment by joshmoore** [comment]
Where are the changes to the CSV coming from?

**Comment by atarkowska** [comment]
from  	f1822bf

**Pull request closed without merging**
